# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190816_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Ingredient'),
        ),
    ]
