# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20190816_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(to='menu.Ingredient'),
        ),
    ]
